spring.application.name=yingpingsxitong
spring.config.import=optional:file:.env[.properties]
spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/polymarket_db}
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.aop.auto = true
spring.aop.proxy-target-class=true
spring.web.resources.static-locations=classpath:/static/, classpath:/public/
